title: "Xiaolong Jia"
name: "Xiaolong Jia"
description: "Personal website"

# GitHub Pages
url: "https://LyingMoon.github.io"
baseurl: ""

# Theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"
locale: "en-US"

# Plugins supported by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-remote-theme

# Author sidebar/profile
author:
  name: "Xiaolong Jia (Sean)"
  avatar: "/assets/images/Self.jpg"
  bio: "Seeking 26 Robotics Software Engineer Opportunities"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/LyingMoon"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/xiaolong-jia62"

# Simple navigation list (reference)
navigation:
  - title: "Projects"
    url: /projects/
  - title: "Teaching"
    url: /teaching/

# Markdown / formatting
kramdown:
  input: GFM

permalink: /:categories/:title/

# Defaults for content
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Analytics (invisible tracking)
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-N8PMNE1X41"  # Replace with your actual Google Analytics tracking ID
    anonymize_ip: false

# Include custom pages folder
include:
  - _pages

